spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/moduply}
    username: ${POSTGRES_USER_NAME:admin}
    password: ${POSTGRES_PASSWORD:0000}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  batch:
    jdbc:
      initialize-schema: always
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  config:
    import: "optional:file:.env[.properties]"

logging:
  level:
    com.team6.moduply: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.messaging.simp: DEBUG
    org.springframework.web.socket: DEBUG

cors:
  allowed-origins:
    - "http://localhost:[*]"
    - "http://127.0.0.1:[*]"

moduply:
  storage:
    type: ${BINARY_CONTENT_STORAGE_TYPE:local}
