spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moduply
    username: moduply
    password: moduply123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect