spring:
  application:
    name: moduply
  profiles:
    active: local
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
  sql:
    init:
      mode: never
  batch:
    job:
      enabled: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true

logging:
  level:
    root: info

cors:
  allowed-origins:
    - "http://moduply.com"

moduply:
  storage:
    type: ${BINARY_CONTENT_STORAGE_TYPE:s3}
    s3:
      access-key: ${AWS_S3_ACCESS_KEY:}
      secret-key: ${AWS_S3_SECRET_KEY:}
      region: ${AWS_S3_REGION}
      bucket: ${AWS_S3_BUCKET}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600} #기본값:10분
    local:
      root-path: ${LOCAL_STORAGE_ROOT_PATH:./uploads}
      url-prefix: ${LOCAL_STORAGE_URL_PREFIX:/uploads}
  external:
    tmdb:
      base-url: ${TMDB_BASE_URL:https://api.themoviedb.org/3}
      image-base-url: ${TMDB_IMAGE_BASE_URL:https://image.tmdb.org/t/p}
      read-access-token: ${TMDB_READ_ACCESS_TOKEN:}
      connect-timeout-millis: ${TMDB_CONNECT_TIMEOUT_MILLIS:3000}
      read-timeout-millis: ${TMDB_READ_TIMEOUT_MILLIS:10000}
    sports-db:
      base-url: ${SPORTS_DB_BASE_URL:https://www.thesportsdb.com/api/v1/json}
      api-key: ${SPORTS_DB_API_KEY}
      connect-timeout-millis: ${SPORTS_DB_CONNECT_TIMEOUT_MILLIS:3000}
      read-timeout-millis: ${SPORTS_DB_READ_TIMEOUT_MILLIS:10000}
    image:
      connect-timeout-millis: ${EXTERNAL_IMAGE_CONNECT_TIMEOUT_MILLIS:3000}
      read-timeout-millis: ${EXTERNAL_IMAGE_READ_TIMEOUT_MILLIS:10000}
  content:
    batch:
      import:
        enabled: ${CONTENT_IMPORT_BATCH_ENABLED:true}
        cron: ${CONTENT_IMPORT_BATCH_CRON:0 0 2 * * *}
        tmdb-page-start: ${CONTENT_IMPORT_BATCH_TMDB_PAGE_START:1}
        tmdb-page-end: ${CONTENT_IMPORT_BATCH_TMDB_PAGE_END:3}
        tmdb-language: ${CONTENT_IMPORT_BATCH_TMDB_LANGUAGE:ko-KR}
        sports-db-league-ids: ${CONTENT_IMPORT_BATCH_SPORTS_DB_LEAGUE_IDS:4328}
        sports-db-sport: ${CONTENT_IMPORT_BATCH_SPORTS_DB_SPORT:Soccer}
        sports-db-day-offsets:
          - ${CONTENT_IMPORT_BATCH_SPORTS_DB_DAY_OFFSET_PREVIOUS:-1}
          - ${CONTENT_IMPORT_BATCH_SPORTS_DB_DAY_OFFSET_TODAY:0}
          - ${CONTENT_IMPORT_BATCH_SPORTS_DB_DAY_OFFSET_NEXT:1}

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
admin:
  init:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}

watching:
  storage:
    type: redis
