# Logstash Pipeline Configuration
# IntelliJ에서 Nginx 설정으로 인식되어 오류가 표시될 수 있으나 실제 문법 오류가 아님
input {
    beats {
        port => 5044
  }
}

filter {
  grok {
    match => {
      "message" => "%{DATA:timestamp} \[%{DATA:thread}\] %{LOGLEVEL:level}%{SPACE}%{DATA:logger} \[%{DATA:requestId} \| %{DATA:requestMethod} \| %{DATA:requestUri}\] - %{GREEDYDATA:log_message}"
    }
  }

  date {
    match => ["timestamp", "yy-MM-dd HH:mm:ss.SSS"]
    target => "@timestamp"
    timezone => "Asia/Seoul"
  }

  mutate {
    strip => ["requestId", "requestMethod", "requestUri"]
    remove_field => ["timestamp", "message", "host", "agent"]
  }

  if "_grokparsefailure" in [tags] {
    mutate {
      add_field => { "parse_error" => "true" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "moduply-logs-%{+YYYY.MM.dd}"
  }
}